var menuJSON = [
   {
      "Text":"Home",
      "Link":"index.html",
      "ChildMenuItems":[]
   },
   {
      "Text":"Global",
      "Link":"",
      "ChildMenuItems":[
         {
            "Text":"Colours",
            "Link":"#colours",
            "ChildMenuItems":[]
         },
         {
            "Text":"Fonts",
            "Link":"#fonts",
            "ChildMenuItems":[]
         },
         {
           "Text":"Grid",
           "Link":"#grid",
           "ChildMenuItems":[]
         },
         {
            "Text":"Animations",
            "Link":"#animations",
            "ChildMenuItems":[]
         }
      ]
   },
   {
      "Text":"Atoms",
      "Link":"",
      "ChildMenuItems":[
         {
            "Text":"Buttons",
            "Link":"#buttons",
            "ChildMenuItems":[]
         },
         {
           "Text":"Input elements",
           "Link":"#inputs",
           "ChildMenuItems":[]
         },
         {
           "Text":"Text elements",
           "Link":"#text",
           "ChildMenuItems":[]
         },
         {
           "Text":"Icons",
           "Link":"#icons",
           "ChildMenuItems":[]
         },
         {
           "Text":"Table",
           "Link":"#table",
           "ChildMenuItems":[]
         },
         {
           "Text":"Tooltip",
           "Link":"#tooltip",
           "ChildMenuItems":[]
         },
         {
           "Text":"Help dialog",
           "Link":"#help",
           "ChildMenuItems":[]
         },
         {
           "Text":"Dialog",
           "Link":"#dialog",
           "ChildMenuItems":[]
         },
         {
           "Text":"Notification",
           "Link":"#notification",
           "ChildMenuItems":[]
         },
         {
           "Text":"Card",
           "Link":"#card",
           "ChildMenuItems":[]
         }
      ]
   },
   {
     "Text":"Molecules",
     "Link":"",
     "ChildMenuItems":[
       {
         "Text":"Carousel",
         "Link":"#carousel",
         "ChildMenuItems":[]
       }
     ]
   },
   {
     "Text":"Organisms",
     "Link":"",
     "ChildMenuItems":[
       {
         "Text":"Australopeticus",
         "Link":"#nogo",
         "ChildMenuItems":[]
       }
     ]
   },
   {
     "Text":"Build your own",
     "Link":"#nogo",
     "ChildMenuItems": []
   }
]
