var menuJSON = [
   {
      "Text":"Home",
      "Link":"index.html",
      "ChildMenuItems":[]
   },
   {
      "Text":"Global",
      "Link":"",
      "ChildMenuItems":[
         {
            "Text":"Colours",
            "Link":"#colours",
            "ChildMenuItems":[]
         },
         {
            "Text":"Fonts",
            "Link":"#fonts",
            "ChildMenuItems":[]
         },
         {
           "Text":"Grid",
           "Link":"#grid",
           "ChildMenuItems":[]
         },
         {
            "Text":"Animations",
            "Link":"#animations",
            "ChildMenuItems":[]
         }
      ]
   },
   {
      "Text":"Atoms",
      "Link":"",
      "ChildMenuItems":[
        {
          "Text":"Icons",
          "Link":"#icons",
          "ChildMenuItems":[]
        },
        {
          "Text":"Text elements",
          "Link":"#text",
          "ChildMenuItems":[]
        },
        {
          "Text":"Count",
          "Link":"#count",
          "ChildMenuItems":[]
        },
        {
           "Text":"Badge",
           "Link":"#badge",
           "ChildMenuItems":[]
        },
         {
            "Text":"Buttons",
            "Link":"#buttons",
            "ChildMenuItems":[]
         },
         {
           "Text":"Input elements",
           "Link":"#inputs",
           "ChildMenuItems":[]
         },
         {
           "Text":"Checkable label",
           "Link":"#check-label",
           "ChildMenuItems":[]
         },
         {
           "Text":"Checkable box",
           "Link":"#check-box",
           "ChildMenuItems":[]
         },
         {
           "Text":"Tabs",
           "Link":"#tab",
           "ChildMenuItems":[]
         },
         {
           "Text":"Table",
           "Link":"#table",
           "ChildMenuItems":[]
         },
         {
           "Text":"Tooltip",
           "Link":"#tooltip",
           "ChildMenuItems":[]
         },
         {
           "Text":"Help dialog",
           "Link":"#help",
           "ChildMenuItems":[]
         },
         {
           "Text":"Dialog",
           "Link":"#dialog",
           "ChildMenuItems":[]
         },
         {
           "Text":"Notification",
           "Link":"#notification",
           "ChildMenuItems":[]
         },
         {
           "Text":"Card",
           "Link":"#card",
           "ChildMenuItems":[]
         }
      ]
   },
   {
     "Text":"Molecules",
     "Link":"",
     "ChildMenuItems":[
       {
         "Text":"Row",
         "Link":"#row",
         "ChildMenuItems":[]
       },
       {
         "Text":"Column",
         "Link":"#col",
         "ChildMenuItems":[]
       },
       {
         "Text":"Section",
         "Link":"#section",
         "ChildMenuItems":[]
       },
       {
         "Text":"Tab-bar",
         "Link":"#tab-bar",
         "ChildMenuItems":[]
       },
       {
         "Text":"Tree",
         "Link":"#tree",
         "ChildMenuItems":[]
       },
       {
         "Text":"Expanding box",
         "Link":"#expand-box",
         "ChildMenuItems":[]
       },
       {
         "Text":"Pagination",
         "Link":"#pagination",
         "ChildMenuItems":[]
       },
       {
         "Text":"Carousel",
         "Link":"#carousel",
         "ChildMenuItems":[]
       }
     ]
   },
   {
     "Text":"Organisms",
     "Link":"",
     "ChildMenuItems":[
       {
         "Text":"Log in",
         "Link":"#login",
         "ChildMenuItems":[]
       },
       {
         "Text":"Global search",
         "Link":"#global-search",
         "ChildMenuItems":[]
       }
     ]
   },
   {
     "Text":"Build your own",
     "Link":"#nogo",
     "ChildMenuItems": []
   }
]
